export const IpcChannel = {
  FILE_ADD: 'FILE_ADD',
  FILE_SAVE: 'FILE_SAVE',

  FILE_PUT: 'FILE_PUT',
  FILE_PUT_SUCCESS: 'FILE_PUT_SUCCESS',
  FILE_PUT_ERROR: 'FILE_PUT_ERROR',

  FILE_DEAL: 'FILE_DEAL',
  SAVED_FILE: 'SAVED_FILE',

  MAIN_ERROR: 'MAIN_ERROR'
}